### ISSUE TITLE
Supporting SSSD and optional databases

### ISSUE THREAD

**Issue by treydock** [ghoneycutt/puppet-module-nsswitch#28]
I'm curious what level of changes to this module would be accepted in a PR to support 'sssd'.  The simplest I'm implementing is to add a parameter called `ldap_nss_module` which defaults to `ldap` but can be changed to `sssd`.  However in some of my environments I do not enable SSSD to manage automount, for example, so leaving some lines in nsswitch.conf to only have `files` would be ideal since SSSD's supported services are individually enabled.

A few more extensive "refactor" ideas:

1. Add a parameter for each database in nsswitch.conf, for example `ensure_ldap_passwd`, `ensure_sssd_passwd`, etc.  That list of parameters could get long.
2. Replace current ensure parameters with ones like `passwd`, `shadow`, etc that is either a string or array that is joined to form a string used in the template.

**Comment by ghoneycutt** [comment]
This module is not being accepted as an approved module by Puppet Labs in favor of https://github.com/trlinkin/puppet-nsswitch

I am still supporting this module for bug fixes or simple feature updates but do not want to accept any large refactors as my goal is to move toward using Thomas's module.

Issues preventing me from using it include OS support and its lack of any spec tests. Suggest targeting any many refactors against that. Though, again, I'll be supporting this module for awhile until Thomas's has spec tests and OS support parity. I'm not in agreement with Puppet Labs approving a module with no testing and as such cannot recommend using it until it has tests.

**Comment by treydock** [comment]
I've gone the route of using the module mentioned by @ghoneycutt , which doesn't have the convenient parameters like `ensure_sssd` as was proposed, but allows pretty much any nsswitch.conf configuration.

My Hiera config

```yaml
nsswitch::passwd:
  - 'files'
  - 'sss'
nsswitch::shadow:
  - 'files'
  - 'sss'
nsswitch::group:
  - 'files'
  - 'sss'
nsswitch::services:
  - 'files'
  - 'sss'
nsswitch::netgroup:
  - 'files'
  - 'sss'
nsswitch::sudoers:
  - 'files'
  - 'sss'
```
