### ISSUE TITLE
sssd support for sudoers

### ISSUE THREAD

**Issue by jyaworski** [ghoneycutt/puppet-module-nsswitch#36]
In recent versions of sudo and sssd, sudo can query sssd for rules.

http://www.freeipa.org/images/7/77/Freeipa30_SSSD_SUDO_Integration.pdf

Can the template be modified to accept a sudo_real?

**Comment by ghoneycutt** [comment]
Right on, I would appreciate a pull request with this functionality. For the PR to be merged it needs to have any added parameters documented in the README, validation of those parameters and spec tests.

**Comment by ghoneycutt** [comment]
Functionality released in v1.4.0
